# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'suggestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10suggestion.proto\x12\x16\x65mail.notifications.v1\"D\n\x0c\x45mailMessage\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x14\n\x0csender_email\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"f\n\x0cVibeAnalysis\x12\x14\n\x0cprimary_vibe\x18\x01 \x01(\t\x12\x15\n\rurgency_level\x18\x02 \x01(\t\x12\x1b\n\x13\x63ommunication_style\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"\x99\x02\n\x12SuggestionAnalysis\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x13\n\x0bsender_name\x18\x02 \x01(\t\x12\x14\n\x0csender_email\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x18\n\x10suggested_action\x18\x05 \x01(\t\x12\x32\n\x04vibe\x18\x06 \x01(\x0b\x32$.email.notifications.v1.VibeAnalysis\x12\x13\n\x0b\x64raft_reply\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12>\n\x10original_message\x18\t \x01(\x0b\x32$.email.notifications.v1.EmailMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILMESSAGE']._serialized_start=44
  _globals['_EMAILMESSAGE']._serialized_end=112
  _globals['_VIBEANALYSIS']._serialized_start=114
  _globals['_VIBEANALYSIS']._serialized_end=216
  _globals['_SUGGESTIONANALYSIS']._serialized_start=219
  _globals['_SUGGESTIONANALYSIS']._serialized_end=500
# @@protoc_insertion_point(module_scope)
